# Generated by Django 5.2.5 on 2025-08-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="utni_price",
        ),
    ]
