# Generated by Django 5.2.5 on 2025-08-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_price_product_utni_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="utni_price",
            new_name="unit_price",
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="-"),
            preserve_default=False,
        ),
    ]
